apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: jcydev-deokji
patchesStrategicMerge:
- ingress.yaml
resources:
- ../../base
- namespace.yaml
images:
- name: jcy0308/deokji
  newTag: 3a05113405ec3b77c04d2e6644021bdd4774af1a
