apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: dev
patchesStrategicMerge:
- ingress.yaml
- deployment.yaml
- service.yaml
resources:
- ../../base
images:
- name: jcy0308/deokji
  newTag: 1ffc2d30db7daff21076ac818a2097e4e6832da3
