apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: dev
patchesStrategicMerge:
- ingress.yaml
- deployment.yaml
- service.yaml
resources:
- ../../base
images:
- name: jcy0308/deokji
  newTag: 1be337e21f1b965530cc3e2fc3b5c6a601e40c11
