apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: prod
patchesStrategicMerge:
- ingress.yaml
resources:
- ../../base
images:
- name: jcy0308/deokji
  newTag: c681a69ce96c0e4f1ef0f58bde86533f7667f322
